### ISSUE TITLE
Rules

### ISSUE THREAD

**Issue by jtljac** [jtljac/me5e#2]
Setup a system that replaces the actives effects system to allow lots more options.
Idea stolen from the [Pf2e system](https://github.com/foundryvtt/pf2e)

# How are they different?
The Rules system should majorly behave similarly to the Active Effects system, allowing modifications to the actors data. The main feature of the Rules system however is to allow modifications of the actors data at many different stages of the actor's data preparation, including one-time-only during initialisation, when certain hooks (like round turnover) are called, and more.
This will allow plenty of automation, like automatically handling the temporary hp in the [Warlord's Bloodrage feat](https://www.n7.world/feats/warlords-blood-rage)

# Effect Item
To take up the slack of the Active Effects system, a new item should be added, an Effect Item, that exclusively holds a rule, this will then be what the user can add to their character sheets. This will also allow premaking effects that can be put into a compendium.

# Predicates
The last peice to making the Rules System incredibly powerful is the ability to control when a Rule is allowed to execute. A Predicate will contain a condition and only allow the Rule to execute when the conditions are met. Predicates will also be able to be compounded together in order to allow multiple conditions to be checked at once.

# Rule Ideas
- AE-like Rule
  - The stand in for Active Effects
  - Should allow changes to be made to the actor in multiple places
    - When active effects usually happen
    - After derrived data has been calculated
- Modifier Rule
  - Adds a [Modifier]() to an actor
  - Should enforce a predicate that checks the actor is a character
- OnCreate Rule
  - Makes a database update to the actor when the rule is added
- OnTurnStart Rule
  - Allow doing something when the affected actor's turn starts

# Predicate Ideas
- Logical Comparison predicates
- And Predicate
- Or Predicate
- Xor Predicate
- Not Predicate
- HasItem Predicate
- IsType Predicate

# TODO:
- [ ] Implement Rules system
- [ ] Document Rules System
- [ ] Implement Effect Item
- [ ] Implement Effect UI
## Rules
- [ ] AE-Like Rule
- [ ] Modifier Rule

## Predicates
- [ ] Implement HasItem Predicate
